---
abstract: 'generates Type::Tiny types out of JSON schemas'
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Path::Tiny: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.040, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JSON-Schema-AsType
provides:
  JSON::Schema::AsType:
    file: lib/JSON/Schema/AsType.pm
    version: v0.0.1
  JSON::Schema::AsType::Draft3:
    file: lib/JSON/Schema/AsType/Draft3.pm
    version: v0.0.1
  JSON::Schema::AsType::Draft4:
    file: lib/JSON/Schema/AsType/Draft4.pm
    version: v0.0.1
requires:
  Clone: '0'
  JSON: '0'
  LWP::Simple: '0'
  List::MoreUtils: '0'
  List::Util: '0'
  Moose: '0'
  Moose::Role: '0'
  Moose::Util: '0'
  MooseX::MungeHas: '0'
  Scalar::Util: '0'
  Type::Tiny: '0'
  Type::Tiny::Class: '0'
  Type::Utils: '0'
  Types::Standard: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/yanick/JSON-Schema-AsType/issues
  homepage: https://github.com/yanick/JSON-Schema-AsType
  repository: https://github.com/yanick/JSON-Schema-AsType.git
version: 0.0.1
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
x_contributors:
  - 'Yanick Champoux <yanick@cpan.org>'
